# -*- coding: utf-8 -*-
"""airflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N60kVR32rBRGDCQpTCkezfVZ9XftjQ3R
"""

pip install schedule

import datetime as dt
import schedule

def f1():
  print('копируем выгрузку из postgre за последние 7 дней')

def f2():
  print('копируем выгрузку из mongodb за последние 7 дней')

def f3():
  print('удаляем пустые')
  print('удаляем лишние стоблцы')

def f4():
  print('сохраняем в sqlite каждый из 4 датафреймов')
  df2.to_sql(name='users', con=engine, if_exists='append')

"""Формируем порядок вызова функций"""

def DAG2():
  print('time_start:', dt.datetime.now())
  f1()
  f2()
  f3()
  f4()
  print('time_end:', dt.datetime.now())
  print('-' * 20)

DAG2()

"""И запускаем на выполнение по расписанию"""

schedule.every(7).weeks.do(DAG2)

while True:
    schedule.run_pending()